permalink: pretty
url: http://milesandkilo.com
markdown: kramdown
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Mike Burns"
